export const jobtitles: string[] = [
  "accountant",
  "actor",
  "actuary",
  "adhesive bonding machine tender",
  "adjudicator",
  "administrative assistant",
  "administrative services manager",
  "adult education teacher",
  "advertising manager",
  "advertising sales agent",
  "aerobics instructor",
  "aerospace engineer",
  "aerospace engineering technician",
  "agent",
  "agricultural engineer",
  "agricultural equipment operator",
  "agricultural grader",
  "agricultural inspector",
  "agricultural manager",
  "agricultural sciences teacher",
  "agricultural sorter",
  "agricultural technician",
  "agricultural worker",
  "air conditioning installer",
  "air conditioning mechanic",
  "air traffic controller",
  "aircraft cargo handling supervisor",
  "aircraft mechanic",
  "aircraft service technician",
  "airline copilot",
  "airline pilot",
  "ambulance dispatcher",
  "ambulance driver",
  "amusement machine servicer",
  "anesthesiologist",
  "animal breeder",
  "animal control worker",
  "animal scientist",
  "animal trainer",
  "animator",
  "answering service operator",
  "anthropologist",
  "apparel patternmaker",
  "apparel worker",
  "arbitrator",
  "archeologist",
  "architect",
  "architectural drafter",
  "architectural manager",
  "archivist",
  "art director",
  "art teacher",
  "artist",
  "assembler",
  "astronomer",
  "athlete",
  "athletic trainer",
  "ATM machine repairer",
  "atmospheric scientist",
  "attendant",
  "audio and video equipment technician",
  "audio-visual and multimedia collections specialist",
  "audiologist",
  "auditor",
  "author",
  "auto damage insurance appraiser",
  "automotive and watercraft service attendant",
  "automotive glass installer",
  "automotive mechanic",
  "avionics technician",
  "baggage porter",
  "bailiff",
  "baker",
  "barback",
  "barber",
  "bartender",
  "basic education teacher",
  "behavioral disorder counselor",
  "bellhop",
  "bench carpenter",
  "bicycle repairer",
  "bill and account collector",
  "billing and posting clerk",
  "biochemist",
  "biological technician",
  "biomedical engineer",
  "biophysicist",
  "blaster",
  "blending machine operator",
  "blockmason",
  "boiler operator",
  "boilermaker",
  "bookkeeper",
  "boring machine tool tender",
  "brazer",
  "brickmason",
  "bridge and lock tender",
  "broadcast news analyst",
  "broadcast technician",
  "brokerage clerk",
  "budget analyst",
  "building inspector",
  "bus mechanic",
  "butcher",
  "buyer",
  "cabinetmaker",
  "cafeteria attendant",
  "cafeteria cook",
  "camera operator",
  "camera repairer",
  "cardiovascular technician",
  "cargo agent",
  "carpenter",
  "carpet installer",
  "cartographer",
  "cashier",
  "caster",
  "ceiling tile installer",
  "cellular equipment installer",
  "cement mason",
  "channeling machine operator",
  "chauffeur",
  "checker",
  "chef",
  "chemical engineer",
  "chemical plant operator",
  "chemist",
  "chemistry teacher",
  "chief executive",
  "child social worker",
  "childcare worker",
  "chiropractor",
  "choreographer",
  "civil drafter",
  "civil engineer",
  "civil engineering technician",
  "claims adjuster",
  "claims examiner",
  "claims investigator",
  "cleaner",
  "clinical laboratory technician",
  "clinical laboratory technologist",
  "clinical psychologist",
  "coating worker",
  "coatroom attendant",
  "coil finisher",
  "coil taper",
  "coil winder",
  "coin machine servicer",
  "commercial diver",
  "commercial pilot",
  "commodities sales agent",
  "communications equipment operator",
  "communications teacher",
  "community association manager",
  "community service manager",
  "compensation and benefits manager",
  "compliance officer",
  "composer",
  "computer hardware engineer",
  "computer network architect",
  "computer operator",
  "computer programmer",
  "computer science teacher",
  "computer support specialist",
  "computer systems administrator",
  "computer systems analyst",
  "concierge",
  "conciliator",
  "concrete finisher",
  "conservation science teacher",
  "conservation scientist",
  "conservation worker",
  "conservator",
  "construction inspector",
  "construction manager",
  "construction painter",
  "construction worker",
  "continuous mining machine operator",
  "convention planner",
  "conveyor operator",
  "cook",
  "cooling equipment operator",
  "copy marker",
  "correctional officer",
  "correctional treatment specialist",
  "correspondence clerk",
  "correspondent",
  "cosmetologist",
  "cost estimator",
  "costume attendant",
  "counseling psychologist",
  "counselor",
  "courier",
  "chef",
  "driver",
  "sales",
  "goverment",
  "programmer",
  "developer",
  "care",
  "work from home",
  "reporter",
  "c# developer",
  "react developer",
  "reporter",
  "court reporter",
  "craft artist",
  "crane operator",
  "credit analyst",
  "credit checker",
  "credit counselor",
  "criminal investigator",
  "criminal justice teacher",
  "crossing guard",
  "curator",
  "custom sewer",
  "customer service representative",
  "cutter",
  "cutting machine operator",
  "dancer",
  "data entry keyer",
  "database administrator",
  "decorating worker",
  "delivery services driver",
  "demonstrator",
  "dental assistant",
  "dental hygienist",
  "dental laboratory technician",
  "dentist",
  "derrick operator",
  "designer",
  "desktop publisher",
  "detective",
  "diagnostic medical sonographer",
  "die maker",
  "diesel engine specialist",
  "dietetic technician",
  "dietitian",
  "dinkey operator",
  "director",
  "dishwasher",
  "dispatcher",
  "door-to-door sales worker",
  "drafter",
  "dragline operator",
  "drama teacher",
  "dredge operator",
  "dressing room attendant",
  "dressmaker",
  "drier operator",
  "drilling machine tool operator",
  "dry-cleaning worker",
  "drywall installer",
  "dyeing machine operator",
  "earth driller",
  "economics teacher",
  "economist",
  "editor",
  "education administrator",
  "electric motor repairer",
  "electrical electronics drafter",
  "electrical engineer",
  "electrical equipment assembler",
  "electrical installer",
  "electrical power-line installer",
  "electrician",
  "electro-mechanical technician",
  "elementary school teacher",
  "elevator installer",
  "elevator repairer",
  "embalmer",
  "emergency management director",
  "emergency medical technician",
  "engine assembler",
  "engineer",
  "engineering manager",
  "engineering teacher",
  "english language teacher",
  "engraver",
  "entertainment attendant",
  "environmental engineer",
  "environmental science teacher",
  "environmental scientist",
  "epidemiologist",
  "escort",
  "etcher",
  "event planner",
  "excavating operator",
  "executive administrative assistant",
  "executive secretary",
  "exhibit designer",
  "expediting clerk",
  "explosives worker",
  "extraction worker",
  "fabric mender",
  "fabric patternmaker",
  "fabricator",
  "faller",
  "family practitioner",
  "family social worker",
  "family therapist",
  "farm advisor",
  "farm equipment mechanic",
  "farm labor contractor",
  "farmer",
  "farmworker",
  "fashion designer",
  "fast food cook",
  "fence erector",
  "fiberglass fabricator",
  "fiberglass laminator",
  "file clerk",
  "filling machine operator",
  "film and video editor",
  "financial analyst",
  "financial examiner",
  "financial manager",
  "financial services sales agent",
  "fine artist",
  "fire alarm system installer",
  "fire dispatcher",
  "fire inspector",
  "fire investigator",
  "firefighter",
  "fish and game warden",
  "fish cutter",
  "fish trimmer",
  "fisher",
  "fitness studies teacher",
  "fitness trainer",
  "flight attendant",
  "floor finisher",
  "floor layer",
  "floor sander",
  "floral designer",
  "food batchmaker",
  "food cooking machine operator",
  "food preparation worker",
  "food science technician",
  "food scientist",
  "food server",
  "food service manager",
  "food technologist",
  "foreign language teacher",
  "foreign literature teacher",
  "forensic science technician",
  "forest fire inspector",
  "forest fire prevention specialist",
  "forest worker",
  "forester",
  "forestry teacher",
  "forging machine setter",
  "foundry coremaker",
  "freight agent",
  "freight mover",
  "fundraising manager",
  "funeral attendant",
  "funeral director",
  "funeral service manager",
  "furnace operator",
  "furnishings worker",
  "furniture finisher",
  "gaming booth cashier",
  "gaming cage worker",
  "gaming change person",
  "gaming dealer",
  "gaming investigator",
  "gaming manager",
  "gaming surveillance officer",
  "garment mender",
  "garment presser",
  "gas compressor",
  "gas plant operator",
  "gas pumping station operator",
  "general manager",
  "general practitioner",
  "geographer",
  "geography teacher",
  "geological engineer",
  "geological technician",
  "geoscientist",
  "glazier",
  "government program eligibility interviewer",
  "graduate teaching assistant",
  "graphic designer",
  "groundskeeper",
  "groundskeeping worker",
  "gynecologist",
  "hairdresser",
  "hairstylist",
  "hand grinding worker",
  "hand laborer",
  "hand packager",
  "hand packer",
  "hand polishing worker",
  "hand sewer",
  "hazardous materials removal worker",
  "head cook",
  "health and safety engineer",
  "health educator",
  "health information technician",
  "health services manager",
  "health specialties teacher",
  "healthcare social worker",
  "hearing officer",
  "heat treating equipment setter",
  "heating installer",
  "heating mechanic",
  "heavy truck driver",
  "highway maintenance worker",
  "historian",
  "history teacher",
  "hoist and winch operator",
  "home appliance repairer",
  "home economics teacher",
  "home entertainment installer",
  "home health aide",
  "home management advisor",
  "host",
  "hostess",
  "hostler",
  "hotel desk clerk",
  "housekeeping cleaner",
  "human resources assistant",
  "human resources manager",
  "human service assistant",
  "hunter",
  "hydrologist",
  "illustrator",
  "industrial designer",
  "industrial engineer",
  "industrial engineering technician",
  "industrial machinery mechanic",
  "industrial production manager",
  "industrial truck operator",
  "industrial-organizational psychologist",
  "information clerk",
  "information research scientist",
  "information security analyst",
  "information systems manager",
  "inspector",
  "instructional coordinator",
  "instructor",
  "insulation worker",
  "insurance claims clerk",
  "insurance sales agent",
  "insurance underwriter",
  "intercity bus driver",
  "interior designer",
  "internist",
  "interpreter",
  "interviewer",
  "investigator",
  "jailer",
  "janitor",
  "jeweler",
  "judge",
  "judicial law clerk",
  "kettle operator",
  "kiln operator",
  "kindergarten teacher",
  "laboratory animal caretaker",
  "landscape architect",
  "landscaping worker",
  "lathe setter",
  "laundry worker",
  "law enforcement teacher",
  "law teacher",
  "lawyer",
  "layout worker",
  "leather worker",
  "legal assistant",
  "legal secretary",
  "legislator",
  "librarian",
  "library assistant",
  "library science teacher",
  "library technician",
  "licensed practical nurse",
  "licensed vocational nurse",
  "life scientist",
  "lifeguard",
  "light truck driver",
  "line installer",
  "literacy teacher",
  "literature teacher",
  "loading machine operator",
  "loan clerk",
  "loan interviewer",
  "loan officer",
  "lobby attendant",
  "locker room attendant",
  "locksmith",
  "locomotive engineer",
  "locomotive firer",
  "lodging manager",
  "log grader",
  "logging equipment operator",
  "logistician",
  "machine feeder",
  "machinist",
  "magistrate judge",
  "magistrate",
  "maid",
  "mail clerk",
  "mail machine operator",
  "mail superintendent",
  "maintenance painter",
  "maintenance worker",
  "makeup artist",
  "management analyst",
  "manicurist",
  "manufactured building installer",
  "mapping technician",
  "marble setter",
  "marine engineer",
  "marine oiler",
  "market research analyst",
  "marketing manager",
  "marketing specialist",
  "carpenter",
  "doctor",
  "nhs",
  "mover",
  "marriage therapist",
  "massage therapist",
  "material mover",
  "materials engineer",
  "materials scientist",
  "mathematical science teacher",
  "mathematical technician",
  "mathematician",
  "maxillofacial surgeon",
  "measurer",
  "meat cutter",
  "meat packer",
  "meat trimmer",
  "mechanical door repairer",
  "mechanical drafter",
  "mechanical engineer",
  "mechanical engineering technician",
  "mediator",
  "medical appliance technician",
  "medical assistant",
  "medical equipment preparer",
  "medical equipment repairer",
  "medical laboratory technician",
  "medical laboratory technologist",
  "medical records technician",
  "medical scientist",
  "medical secretary",
  "medical services manager",
  "medical transcriptionist",
  "meeting planner",
  "mental health counselor",
  "mental health social worker",
  "merchandise displayer",
  "messenger",
  "metal caster",
  "metal patternmaker",
  "metal pickling operator",
  "metal pourer",
  "metal worker",
  "metal-refining furnace operator",
  "metal-refining furnace tender",
  "meter reader",
  "microbiologist",
  "middle school teacher",
  "milling machine setter",
  "millwright",
  "mine cutting machine operator",
  "mine shuttle car operator",
  "mining engineer",
  "mining safety engineer",
  "mining safety inspector",
  "mining service unit operator",
  "mixing machine setter",
  "mobile heavy equipment mechanic",
  "mobile home installer",
  "model maker",
  "model",
  "molder",
  "mortician",
  "motel desk clerk",
  "motion picture projectionist",
  "motorboat mechanic",
  "motorboat operator",
  "motorboat service technician",
  "motorcycle mechanic",
  "multimedia artist",
  "museum technician",
  "music director",
  "music teacher",
  "musical instrument repairer",
  "musician",
  "natural sciences manager",
  "naval architect",
  "network systems administrator",
  "new accounts clerk",
  "news vendor",
  "nonfarm animal caretaker",
  "nuclear engineer",
  "nuclear medicine technologist",
  "nuclear power reactor operator",
  "nuclear technician",
  "nursing aide",
  "nursing instructor",
  "nursing teacher",
  "nutritionist",
  "obstetrician",
  "occupational health and safety specialist",
  "occupational health and safety technician",
  "occupational therapist",
  "occupational therapy aide",
  "occupational therapy assistant",
  "offbearer",
  "office clerk",
  "office machine operator",
  "operating engineer",
  "operations manager",
  "operations research analyst",
  "ophthalmic laboratory technician",
  "optician",
  "optometrist",
  "oral surgeon",
  "order clerk",
  "order filler",
  "orderly",
  "ordnance handling expert",
  "orthodontist",
  "orthotist",
  "outdoor power equipment mechanic",
  "oven operator",
  "packaging machine operator",
  "painter ",
  "painting worker",
  "paper goods machine setter",
  "paperhanger",
  "paralegal",
  "paramedic",
  "parking enforcement worker",
  "parking lot attendant",
  "parts salesperson",
  "paving equipment operator",
  "payroll clerk",
  "pediatrician",
  "pedicurist",
  "personal care aide",
  "personal chef",
  "personal financial advisor",
  "pest control worker",
  "pesticide applicator",
  "pesticide handler",
  "pesticide sprayer",
  "petroleum engineer",
  "petroleum gauger",
  "petroleum pump system operator",
  "petroleum refinery operator",
  "petroleum technician",
  "pharmacist",
  "pharmacy aide",
  "pharmacy technician",
  "philosophy teacher",
  "photogrammetrist",
  "photographer",
  "photographic process worker",
  "photographic processing machine operator",
  "physical therapist aide",
  "physical therapist assistant",
  "physical therapist",
  "physician assistant",
  "physician",
  "physicist",
  "physics teacher",
  "pile-driver operator",
  "pipefitter",
  "pipelayer",
  "planing machine operator",
  "planning clerk",
  "plant operator",
  "plant scientist",
  "plasterer",
  "plastic patternmaker",
  "plastic worker",
  "plumber",
  "podiatrist",
  "police dispatcher",
  "police officer",
  "policy processing clerk",
  "political science teacher",
  "political scientist",
  "postal service clerk",
  "postal service mail carrier",
  "postal service mail processing machine operator",
  "postal service mail processor",
  "postal service mail sorter",
  "postmaster",
  "postsecondary teacher",
  "poultry cutter",
  "poultry trimmer",
  "power dispatcher",
  "power distributor",
  "power plant operator",
  "power tool repairer",
  "precious stone worker",
  "precision instrument repairer",
  "prepress technician",
  "preschool teacher",
  "priest",
  "print binding worker",
  "printing press operator",
  "private detective",
  "probation officer",
  "procurement clerk",
  "producer",
  "product promoter",
  "production clerk",
  "production occupation",
  "proofreader",
  "property manager",
  "prosthetist",
  "prosthodontist",
  "psychiatric aide",
  "psychiatric technician",
  "psychiatrist",
  "psychologist",
  "psychology teacher",
  "public relations manager",
  "public relations specialist",
  "pump operator",
  "purchasing agent",
  "purchasing manager",
  "radiation therapist",
  "radio announcer",
  "radio equipment installer",
  "radio operator",
  "radiologic technician",
  "radiologic technologist",
  "rail car repairer",
  "rail transportation worker",
  "rail yard engineer",
  "rail-track laying equipment operator",
  "railroad brake operator",
  "railroad conductor",
  "railroad police",
  "rancher",
  "real estate appraiser",
  "real estate broker",
  "real estate manager",
  "real estate sales agent",
  "receiving clerk",
  "receptionist",
  "record clerk",
  "recreation teacher",
  "recreation worker",
  "recreational therapist",
  "recreational vehicle service technician",
  "recyclable material collector",
  "referee",
  "refractory materials repairer",
  "refrigeration installer",
  "refrigeration mechanic",
  "refuse collector",
  "regional planner",
  "registered nurse",
  "rehabilitation counselor",
  "reinforcing iron worker",
  "reinforcing rebar worker",
  "religion teacher",
  "religious activities director",
  "religious worker",
  "rental clerk",
  "repair worker",
  "reporter",
  "residential advisor",
  "resort desk clerk",
  "respiratory therapist",
  "respiratory therapy technician",
  "retail buyer",
  "retail salesperson",
  "revenue agent",
  "rigger",
  "rock splitter",
  "rolling machine tender",
  "roof bolter",
  "roofer",
  "rotary drill operator",
  "roustabout",
  "safe repairer",
  "sailor",
  "sales engineer",
  "sales manager",
  "sales representative",
  "sampler",
  "sawing machine operator",
  "scaler",
  "school bus driver",
  "school psychologist",
  "school social worker",
  "scout leader",
  "sculptor",
  "secondary education teacher",
  "secondary school teacher",
  "secretary",
  "securities sales agent",
  "security guard",
  "security system installer",
  "segmental paver",
  "self-enrichment education teacher",
  "semiconductor processor",
  "septic tank servicer",
  "set designer",
  "sewer pipe cleaner",
  "sewing machine operator",
  "shampooer",
  "shaper",
  "sheet metal worker",
  "sheriff's patrol officer",
  "ship captain",
  "ship engineer",
  "ship loader",
  "shipmate",
  "shipping clerk",
  "shoe machine operator",
  "shoe worker",
  "short order cook",
  "signal operator",
  "signal repairer",
  "singer",
  "ski patrol",
  "skincare specialist",
  "slaughterer",
  "slicing machine tender",
  "slot supervisor",
  "social science research assistant",
  "social sciences teacher",
  "social scientist",
  "social service assistant",
  "social service manager",
  "social work teacher",
  "social worker",
  "sociologist",
  "sociology teacher",
  "software developer",
  "software engineer",
  "soil scientist",
  "solderer",
  "sorter",
  "sound engineering technician",
  "space scientist",
  "special education teacher",
  "speech-language pathologist",
  "sports book runner",
  "sports entertainer",
  "sports performer",
  "stationary engineer",
  "statistical assistant",
  "statistician",
  "steamfitter",
  "stock clerk",
  "stock mover",
  "stonemason",
  "street vendor",
  "streetcar operator",
  "structural iron worker",
  "structural metal fabricator",
  "structural metal fitter",
  "structural steel worker",
  "stucco mason",
  "substance abuse counselor",
  "substance abuse social worker",
  "subway operator",
  "surfacing equipment operator",
  "surgeon",
  "surgical technologist",
  "survey researcher",
  "surveying technician",
  "surveyor",
  "switch operator",
  "switchboard operator",
  "tailor",
  "tamping equipment operator",
  "tank car loader",
  "taper",
  "tax collector",
  "tax examiner",
  "tax preparer",
  "taxi driver",
  "teacher assistant",
  "teacher",
  "team assembler",
  "technical writer",
  "telecommunications equipment installer",
  "telemarketer",
  "telephone operator",
  "television announcer",
  "teller",
  "terrazzo finisher",
  "terrazzo worker",
  "tester",
  "textile bleaching operator",
  "textile cutting machine setter",
  "textile knitting machine setter",
  "textile presser",
  "textile worker",
  "therapist",
  "ticket agent",
  "ticket taker",
  "tile setter",
  "timekeeping clerk",
  "timing device assembler",
  "tire builder",
  "tire changer",
  "tire repairer",
  "title abstractor",
  "title examiner",
  "title searcher",
  "tobacco roasting machine operator",
  "tool filer",
  "tool grinder",
  "tool maker",
  "tool sharpener",
  "tour guide",
  "tower equipment installer",
  "tower operator",
  "track switch repairer",
  "tractor operator",
  "tractor-trailer truck driver",
  "traffic clerk",
  "traffic technician",
  "training and development manager",
  "training and development specialist",
  "transit police",
  "translator",
  "transportation equipment painter",
  "transportation inspector",
  "transportation security screener",
  "transportation worker",
  "trapper",
  "travel agent",
  "travel clerk",
  "travel guide",
  "tree pruner",
  "tree trimmer",
  "trimmer",
  "truck loader",
  "truck mechanic",
  "tuner",
  "turning machine tool operator",
  "typist",
  "umpire",
  "undertaker",
  "upholsterer",
  "urban planner",
  "usher",
  "valve installer",
  "vending machine servicer",
  "veterinarian",
  "veterinary assistant",
  "veterinary technician",
  "vocational counselor",
  "vocational education teacher",
  "waiter",
  "waitress",
  "watch repairer",
  "water treatment plant operator",
  "weaving machine setter",
  "web developer",
  "weigher",
  "welder",
  "wellhead pumper",
  "wholesale buyer",
  "wildlife biologist",
  "window trimmer",
  "wood patternmaker",
  "woodworker",
  "word processor",
  "writer",
  "yardmaster",
  "zoologist",
  "Academic librarian",
  "Accountant",
  "Accounting technician",
  "Actuary",
  "Adult nurse",
  "Advertising account executive",
  "Advertising account planner",
  "Advertising copywriter",
  "Advice worker",
  "Advocate (Scotland)",
  "Aeronautical engineer",
  "Agricultural consultant",
  "Agricultural manager",
  "Aid worker/humanitarian worker",
  "Air traffic controller",
  "Airline cabin crew",
  "Amenity horticulturist",
  "Analytical chemist",
  "Animal nutritionist",
  "Animator",
  "Archaeologist",
  "Architect",
  "Architectural technologist",
  "Archivist",
  "Armed forces officer",
  "Aromatherapist",
  "Art therapist",
  "Arts administrator",
  "Auditor",
  "Automotive engineer",
  "Barrister",
  "Barrister’s clerk",
  "Bilingual secretary",
  "Biomedical engineer",
  "Biomedical scientist",
  "Biotechnologist",
  "Brand manager",
  "Broadcasting presenter",
  "Building control officer/surveyor",
  "Building services engineer",
  "Building surveyor",
  "Camera operator",
  "Careers adviser (higher education)",
  "Careers adviser",
  "Careers consultant",
  "Cartographer",
  "Catering manager",
  "Charities administrator",
  "Charities fundraiser",
  "Chemical (process) engineer",
  "Child psychotherapist",
  "Children's nurse",
  "Chiropractor",
  "Civil engineer",
  "Civil Service administrator",
  "Clinical biochemist",
  "Clinical cytogeneticist",
  "Clinical microbiologist",
  "Clinical molecular geneticist",
  "Clinical research associate",
  "Clinical scientist - tissue typing",
  "Clothing and textile technologist",
  "Colour technologist",
  "Commercial horticulturist",
  "Commercial/residential/rural surveyor",
  "Commissioning editor",
  "Commissioning engineer",
  "Commodity broker",
  "Communications engineer",
  "Community arts worker",
  "Community education officer",
  "Community worker",
  "Company secretary",
  "Computer sales support",
  "Computer scientist",
  "Conference organiser",
  "Consultant",
  "Consumer rights adviser",
  "Control and instrumentation engineer",
  "Corporate banker",
  "Corporate treasurer",
  "Counsellor",
  "Courier/tour guide",
  "Court reporter/verbatim reporter",
  "Credit analyst",
  "Crown Prosecution Service lawyer",
  "Crystallographer",
  "Curator",
  "Customs officer",
  "Cyber security specialist",
  "Dance movement therapist",
  "Data analyst",
  "Data scientist",
  "Data visualisation analyst",
  "Database administrator",
  "Debt/finance adviser",
  "Dental hygienist",
  "Dentist",
  "Design engineer",
  "Dietitian",
  "Diplomatic service",
  "Doctor (general practitioner, GP)",
  "Doctor (hospital)",
  "Dramatherapist",
  "Economist",
  "Editorial assistant",
  "Education administrator",
  "Electrical engineer",
  "Electronics engineer",
  "Employment advice worker",
  "Energy conservation officer",
  "Engineering geologist",
  "Environmental education officer",
  "Environmental health officer",
  "Environmental manager",
  "Environmental scientist",
  "Equal opportunities officer",
  "Equality and diversity officer",
  "Ergonomist",
  "Estate agent",
  "European Commission administrators",
  "Exhibition display designer",
  "Exhibition organiser",
  "Exploration geologist",
  "Facilities manager",
  "Field trials officer",
  "Financial manager",
  "Firefighter",
  "Fisheries officer",
  "Fitness centre manager",
  "Food scientist",
  "Food technologist",
  "Forensic scientist",
  "Geneticist",
  "Geographical information systems manager",
  "Geomatics/land surveyor",
  "Government lawyer",
  "Government research officer",
  "Graphic designer",
  "Health and safety adviser",
  "Health and safety inspector",
  "Health promotion specialist",
  "Health service manager",
  "Health visitor",
  "Herbalist",
  "Heritage manager",
  "Higher education administrator",
  "Higher education advice worker",
  "Homeless worker",
  "Horticultural consultant",
  "Hotel manager",
  "Housing adviser",
  "Human resources officer",
  "Hydrologist",
  "Illustrator",
  "Immigration officer",
  "Immunologist",
  "Industrial/product designer",
  "Information scientist",
  "Information systems manager",
  "Information technology/software trainers",
  "Insurance broker",
  "Insurance claims inspector",
  "Insurance risk surveyor",
  "Insurance underwriter",
  "Interpreter",
  "Investment analyst",
  "Investment banker - corporate finance",
  "Investment banker – operations",
  "Investment fund manager",
  "IT consultant",
  "IT support analyst",
  "Journalist",
  "Laboratory technician",
  "Land-based engineer",
  "Landscape architect",
  "Learning disability nurse",
  "Learning mentor",
  "Lecturer (adult education)",
  "Lecturer (further education)",
  "Lecturer (higher education)",
  "Legal executive",
  "Leisure centre manager",
  "Licensed conveyancer",
  "Local government administrator",
  "Local government lawyer",
  "Logistics/distribution manager",
  "Magazine features editor",
  "Magazine journalist",
  "Maintenance engineer",
  "Management accountant",
  "Manufacturing engineer",
  "Manufacturing machine operator",
  "Manufacturing toolmaker",
  "Marine scientist",
  "Market research analyst",
  "Market research executive",
  "Marketing account manager",
  "Marketing assistant",
  "Marketing executive",
  "Marketing manager (social media)",
  "Materials engineer",
  "Materials specialist",
  "Mechanical engineer",
  "Media analyst",
  "Media buyer",
  "Media planner",
  "Medical physicist",
  "Medical representative",
  "Mental health nurse",
  "Metallurgist",
  "Meteorologist",
  "Microbiologist",
  "Midwife",
  "Mining engineer",
  "Mobile developer",
  "Multimedia programmer",
  "Multimedia specialists",
  "Museum education officer",
  "Museum/gallery exhibition officer",
  "Music therapist",
  "Nanoscientist",
  "Nature conservation officer",
  "Naval architect",
  "Network administrator",
  "Nurse",
  "Nutritional therapist",
  "Nutritionist",
  "Occupational therapist",
  "Oceanographer",
  "Office manager",
  "Operational researcher",
  "Orthoptist",
  "Outdoor pursuits manager",
  "Packaging technologist",
  "Paediatric nurse",
  "Paramedic",
  "Patent attorney",
  "Patent examiner",
  "Pension scheme manager",
  "Personal assistant",
  "Petroleum engineer",
  "Pharmacist",
  "Pharmacologist",
  "Pharmacovigilance officer",
  "Photographer",
  "Physiotherapist",
  "Picture researcher",
  "Planning and development surveyor",
  "Planning technician",
  "Plant breeder",
  "Police officer",
  "Political party agent",
  "Political party research officer",
  "Practice nurse",
  "Press photographer",
  "Press sub-editor",
  "Prison officer",
  "Private music teacher",
  "Probation officer",
  "Product development scientist",
  "Production manager",
  "Programme researcher",
  "Project manager",
  "Psychologist (clinical)",
  "Psychologist (educational)",
  "Psychotherapist",
  "Public affairs consultant (lobbyist)",
  "Public affairs consultant (research)",
  "Public house manager",
  "Public librarian",
  "Public relations (PR) officer",
  "QA analyst",
  "Quality assurance manager",
  "Quantity surveyor",
  "Records manager",
  "Recruitment consultant",
  "Recycling officer",
  "Regulatory affairs officer",
  "Research chemist",
  "Research scientist",
  "Restaurant manager",
  "Retail banker",
  "Retail buyer",
  "Retail manager",
  "Retail merchandiser",
  "Retail pharmacist",
  "Sales executive",
  "Sales manager",
  "Scene of crime officer",
  "Secretary",
  "Seismic interpreter",
  "Site engineer",
  "Site manager",
  "Social researcher",
  "Social worker",
  "Software developer",
  "Soil scientist",
  "Solicitor",
  "Speech and language therapist",
  "Sports coach",
  "Sports development officer",
  "Sports therapist",
  "Statistician",
  "Stockbroker",
  "Structural engineer",
  "Systems analyst",
  "Systems developer",
  "Tax inspector",
  "Teacher (nursery/early years)",
  "Teacher (primary)",
  "Teacher (secondary)",
  "Teacher (special educational needs)",
  "Teaching/classroom assistant",
  "Technical author",
  "Technical sales engineer",
  "TEFL/TESL teacher",
  "Television production assistant",
  "Test automation developer",
  "Tour operator",
  "Tourism officer",
  "Tourist information manager",
  "Town and country planner",
  "Toxicologist",
  "Trade union research officer",
  "Trader",
  "Trading standards officer",
  "Training and development officer",
  "Translator",
  "Transportation planner",
  "Travel agent",
  "TV/film/theatre set designer",
  "UX designer",
  "Validation engineer",
  "Veterinary nurse",
  "Veterinary surgeon",
  "Video game designer",
  "Video game developer",
  "Volunteer work organiser",
  "Warehouse manager",
  "Waste disposal officer",
  "Water conservation officer",
  "Water engineer",
  "Web designer",
  "Web developer",
  "Welfare rights adviser",
  "Writer",
  "Youth worker",
  "advisor",
  "finance",
  "Team Leader",
  "ASP.Net, C# Developer",
  "Sales Executive",
  "Lawyer - Family",
  "Warehouse Operative ",
  "Medical",
  "Electrical Design Engineer",
  "Senior Customer Experience Manager ",
  "Software Project Manager",
  "Finance Manager / Controller",
  "Office Manager",
  "Internal Communications and Engagement Manager",
  "ADR LGV1 DRIVER",
  "Junior Accounts Assistant",
  "Critical Care Nurse Band 5 - Archway, London",
  "Senior Accountant",
  "Warehouse Operative",
  "Medical",
  "Children's Registered Manager",
  "Safer Neighbourhood specialist",
  "Care Worker",
  "Class 2 HIAB Driver",
  "Lawyer - Lease Extension / Enfranchisement",
  "MOT Tester",
  "Medical",
  "Employment Lawyer NQ",
  "Digital Marketing Assistant",
  "Trainee Headhunter",
  "Audiologist/Hearing Aid Dispenser - Bournemouth, Dorset",
  "Quantity Surveyor",
  "Lawyer - Leasehold Enfranchisement",
  "Sales Ledger Clerk",
  "HCA Community - Band 2 - Herne Bay",
  "Architectural Technologist",
  "Fitter/Assembly Technician",
  "Cleaning Supervisor",
  "18th Edition / 2391  / JIB card / Electrician",
  "HGV 1 Weekends",
  "Maintenance Engineer",
  "Medical",
  "ER and Policy Specialist",
  "Accounts Assistant",
  "Maintenance Engineer",
  "Private Client Solicitor",
  "Learning Support Assistant - Primary SEN School, Southampton",
  "IT Project Manager",
  "Foster Carer - Exmouth",
  "Therapeutic Care / Support Worker Drivers Only",
  "Development Engineer",
  "Therapeutic Care / Support Worker Drivers Only",
  "Business Consultant/Architect - Core Banking",
  "Warehouse Administrator",
  "Multi Skilled Engineer",
  "Electrical Maintenance Engineer Static",
  "Warehouse Operative - Friday - Sunday",
  "Account Coordinator",
  "Medical",
  "Corporate Tax Senior",
  "GRADUATE CUSTOMER SERVICE CO-ORDINATOR",
  "Maintenance Operative",
  "Night Care Assistant",
  "Care Assistant",
  "Audit Senior",
  "Cover Supervisor",
  "Wellbeing Co-ordinator",
  "Care Assistant",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Semi Senior Accountant -",
  "Registered/Pre Registered Nurses",
  "Activities Co-ordinator",
  "Registered/Pre Registered Nurses",
  "eDisclosure Projects Co-ordinator/eDisclosure Co-ordinator - Relativity",
  "Head Housekeeper",
  "Registered/Pre Registered Nurses",
  "Registered Nurse",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Home Administrator - Financial Administrator",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Registered/Pre Registered Nurses",
  "Supply Primary Teacher",
  "Procurement Manager - Epos Terminal",
  "Nursing Home Manager",
  "Consultancy Role",
  "Cleaner with DBS check",
  "Lawyer - Conveyancing",
  "Mental Health Support Worker - Bank",
  "Graduate Trainee Recruitment Consultant",
  "Doctor",
  "Security Officer",
  "Product Manager",
  "Night Worker",
  "Critical Care Nurse Band 5 - Enfield, London",
  "SQL Database Developer",
  "Master Scheduler",
  "Electrician ",
  "Branch Manager",
  "SEN TA - East London",
  "Night Care Assistant",
  "Customer Services Officer",
  "Critical Care Nurse Band 6 - City of London",
  "Warehouse Operative",
  "Warehouse Operative",
  "Supply Teacher",
  "Warehouse Operative",
  "Regional Manager",
  "Sales Engineer PCB/Electronics",
  "Support Workers / Healthcare Assistants - Milnsbridge, Huddersfield",
  "Category Manager 12 Month FTC",
  "Cleaner",
  "2 day a week Spanish Primary Teacher",
  "Head of Housing Development",
  "Letting Negotiator/Administrator ",
  "Doctor",
  "Workplace Product Owner - 12 Month Contract ",
  "Supply Teacher",
  "Disability Analyst Wigan",
  "Estate Agent Sales Manager ",
  "Chair of the Board",
  "Cleaner",
  "Waking Nights Support Worker",
  "Supply Teacher",
  "Child Care Worker",
  "Backend Java Developer Linux TCP/IP",
  "Senior Payroll Officer",
  "Mortgage and Protection Advisor",
  "Sales Engineer PCB/Electronics",
  "Marketing Executive",
  "Electrician ",
  "Senior UK Compliance Officer",
  "Admin Assistant",
  "Deputy Store Manager",
  "National Sales Manager",
  "Senior Recruitment Consultant",
  "Preceptorship Nurse",
  "Head of Business Intelligence",
  "Teacher of Science Chemistry",
  "Disability Analyst Stirling",
  "Private Client Solicitor - HNW",
  "2nd Line IT Support Technician",
  "Finance admin officers",
  "Electrical/Mechanical Engineer",
  "Business Development Manager",
  "Family & Childcare Solicitor",
  "Mental Health Support Worker - Full Time ",
  "Supply Teacher",
  "Senior Support Worker",
  "SEN TEACHER - ICT / COMPUTER SCIENCE",
  "Commercial Gas Engineer - Static",
  "Remote Mobile Developer iOS & Android",
  "Service Charge Analyst",
  "IT Support Engineer - Newquay- £28,000",
  "Medical",
  "Roofer/Bricklayer - Walsall",
  "CLASS 1 DRIVER",
  "Accounts Assistant ",
  "Assistant Accountant",
  "IT Service Desk Analyst",
  "Corporate Actions Analyst",
  "Cat B Van Driver",
  "Production Operative",
  "Health & Safety Officer",
  "Multi Skilled Tradesman",
  "Supervising Social Worker - Fostering Team",
  "Business Development Manager",
  "Customer Care Coordinator - New Build Housing",
  "Generator Service Engineer",
  "Test Technician",
  "Immigration Solicitor",
  "Medical",
  "Lawyer - Commercial Property Turkish Speaking",
  "SEN TA - with Team Teach",
  "Practice Accounts Assistant",
  "Software Programme Manager",
  "Gas Service Engineer/ Plumber",
  "Senior Quantity Surveyor (Civil Engineering)",
  "QHSE Manager",
  "Wandsworth Council - Senior Social Worker - Child in Need",
  "Disability Analyst Preston",
  "M&E Maintenance Engineer",
  "Learning Support Assistant required for a 1 to 1 role",
  "Senior Designer - PED",
  "Flexible Worker Advisor - Teaching Hospitals NHS Foundation Trust",
  "Supply Teachers",
  "Finance Director",
  "Returns Clerk",
  "Resident Medical Officer",
  "Secondary teaching Assistant",
  "Financial Controller",
  "Partner Integration Manager",
  "Self-Employed Mortgage Advisor - Suffolk Home-Based",
  "Service Co-ordinator",
  "SEND Teaching Assistant",
  "Clinical Trial Physician",
  "Critical Care Nurse Band 5 - Farringdon, London",
  "Customer Collections & Loans Agent - Castlebar",
  "Solutions Architect - 12 Month Contract ",
  "Cleaner",
  "Test Job - Do not apply",
  "Registered Nurse - Functional Assessor",
  "Operative",
  "Supply Teacher",
  "Hygiene Supervisor",
  "Chef de Partie ",
  "DSP Software Engineer, Thames Valley, UK",
  "Property Mantaintence Manager ",
  "HGV 1",
  "Fire Engineer",
  "Telesales Account Manager",
  "Forklift Truck Driver",
  "Test Lead/Manager",
  "Critical Care Nurse Band 6 - Leytonstone, London",
  "Disability Analyst Motherwell",
  "Trainee Recruitment Consultant",
  "Factory Cleaner (NIGHTS)",
  "Functional Assessor - Registered Nurse - Edinburgh, Scotland",
  "Models, Actors, Extras Required for Commercials,TV & Film",
  "Care Assistant",
  "Medical",
  "Work From Home",
  "Senior Care Assistant",
  "HGV Technician - Plymouth ",
  "Quality Manager",
  "Management Accountant ",
  "Design Engineer - Temporary Works (Civil Engineering)",
  "Registered Nurse - Functional Assessor",
  "Mechanical Technician",
  "Paraplanner",
  "Senior Recruitment Consultant - Big Data and Change Management - 25k-35k - London",
  "Digital / IT Recruitment Consultant - £30,000 + South West London - Award Winning Business",
  "Recruitment Consultant - Insurance - £35,000+ - London ",
  "Recruitment Consultant - Life Sciences - London - £28,000 - £38,000",
  "Senior Recruitment Consultant - Actuarial - £35,000 - £50,000 - London",
  "Financial Senior Recruitment Consultant - basic upto 40k",
  "HGV 2 Moffett",
  "HR Business Partner",
  "Regional Manager- Welfare to Work Sector",
  "Assistant Management Accountant",
  "Warehouse Stock Admin Controller",
  "Early Years Teaching Assistant",
  "Trust Recruitment Coordinator - Sheffield Teaching Hospitals NHS Foundation Trust",
  "Lease Restructuring Advisor",
  "Senior Engineer - Civil Engineering ",
  "Chinook Technician",
  "Senior Recruitment Consultant",
  "Disability Analyst Manchester",
  "Lettings Manager",
  "Communications and Marketing Manager",
  "General Manager",
  "Industrial Cleaner",
  "Commercial & Domestic Gas Engineer -",
  "FLEXI BENDI/PIVOT STEER DRIVER REQUIRED ",
  "Engineer or Geologist",
  "Electrical Maintenance Engineer ",
  "Cleaning Supervisor",
  "Quality Administrator",
  "Head of PPC - Digital Marketing Agency - Altrincham",
  "Medical",
  "Project Coordinator",
  "Operations/Financial Manager",
  "Accounts Assistant",
  "Registered Manager  Children's Home",
  "Performance Account Director",
  "Sales Assessor",
  "Panel Wireman",
  "Product Validation Engineer",
  "Underwriter",
  "HR and Payroll Officer",
  "Postperson with driving - Forest Hall Delivery Office NE12 9AA",
  "Postperson with Driving - Oswestry Delivery Office SY10 8GP",
  "Postperson with driving - Darlington Delivery OfficeDL1 1AA",
  "Postperson with Driving - Rochdale Delivery Office ",
  "Postperson with Driving - Bootle Delivery Office",
  "Postperson with Driving - Wembley Highs Delivery Office HA0 2SS",
  "Cleaning Operative - Denbigh Delivery Office LL16 3SA",
  "Postperson with Driving - Manvers Delivery Office S63 5AA",
  "Postperson with Driving - Chorlton Delivery Office ",
  "Postperson with Driving - Immingham Delivery Office DN40 1BL",
  "Postperson with Driving - Dunbar Delivery Office EH42 1AA",
  "Asbestos Analyst",
  "Cleaning Operative Weekend - National Distribution Centre, Northampton NN6 7DD",
  "Postperson with Driving - Sheffield South East Delivery Office S12 2AF",
  "Postperson with driving - Newcastle West Delivery Office NE5 2AA",
  "Postperson with Driving - Glaisdale Parkway Delivery Office NG8 4GB",
  "Residential Park Manager/ warden/ maintenance",
  "Test Administrator - Tunbridge Wells",
  "Test Centre Administrator-Watford",
  "Test Centre Administrator - Stornoway",
  "Test Centre Administrator-Eastbourne",
  "Test Centre Administrator - Sidcup",
  "Test Centre Administrator - Croydon",
  "Car Sales Executive Vacancy",
  "Infrastructure Architect - Azure",
  "Plantarea Buyer/Manager",
  "Disability Analyst Leeds",
];
